/* File: fortran_funcsmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Wed Dec  4 19:45:41 2019
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <math.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *fortran_funcs_error;
static PyObject *fortran_funcs_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
/*need_typedefs*/

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
/*need_typedefs_generated*/

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define CHECKSCALAR(check,tcheck,name,show,var)\
    if (!(check)) {\
        char errstring[256];\
        sprintf(errstring, "%s: "show, "("tcheck") failed for "name, var);\
        PyErr_SetString(fortran_funcs_error,errstring);\
        /*goto capi_fail;*/\
    } else 
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fortran_funcs_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = fortran_funcs_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int float_from_pyobj(float* v,PyObject *obj,const char *errmess) {
    double d=0.0;
    if (double_from_pyobj(&d,obj,errmess)) {
        *v = (float)d;
        return 1;
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(laplace,LAPLACE)(float*,float*,int*,int*);
extern void F_FUNC(interp1,INTERP1)(float*,float*,float*,float*,int*,int*);
extern void F_FUNC(curvature,CURVATURE)(float*,float*,int*,int*,float*);
extern void F_FUNC(zinterp,ZINTERP)(float*,float*,float*,float*,float*,float*,int*,int*,int*,int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/
/*need_callbacks*/

/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** laplace **********************************/
static char doc_f2py_rout_fortran_funcs_laplace[] = "\
fuzz = laplace(stuff,[m,n])\n\nWrapper for ``laplace``.\
\n\nParameters\n----------\n"
"stuff : input rank-2 array('f') with bounds (m,n)\n"
"\nOther Parameters\n----------------\n"
"m : input int, optional\n    Default: shape(stuff,0)\n"
"n : input int, optional\n    Default: shape(stuff,1)\n"
"\nReturns\n-------\n"
"fuzz : rank-2 array('f') with bounds (m,n)";
/* extern void F_FUNC(laplace,LAPLACE)(float*,float*,int*,int*); */
static PyObject *f2py_rout_fortran_funcs_laplace(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *stuff = NULL;
  npy_intp stuff_Dims[2] = {-1, -1};
  const int stuff_Rank = 2;
  PyArrayObject *capi_stuff_tmp = NULL;
  int capi_stuff_intent = 0;
  PyObject *stuff_capi = Py_None;
  float *fuzz = NULL;
  npy_intp fuzz_Dims[2] = {-1, -1};
  const int fuzz_Rank = 2;
  PyArrayObject *capi_fuzz_tmp = NULL;
  int capi_fuzz_intent = 0;
  int m = 0;
  PyObject *m_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  static char *capi_kwlist[] = {"stuff","m","n",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O|OO:fortran_funcs.laplace",\
    capi_kwlist,&stuff_capi,&m_capi,&n_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable stuff */
  ;
  capi_stuff_intent |= F2PY_INTENT_IN;
  capi_stuff_tmp = array_from_pyobj(NPY_FLOAT,stuff_Dims,stuff_Rank,capi_stuff_intent,stuff_capi);
  if (capi_stuff_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 1st argument `stuff' of fortran_funcs.laplace to C/Fortran array" );
  } else {
    stuff = (float *)(PyArray_DATA(capi_stuff_tmp));

  /* Processing variable m */
  if (m_capi == Py_None) m = shape(stuff,0); else
    f2py_success = int_from_pyobj(&m,m_capi,"fortran_funcs.laplace() 1st keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(stuff,0)==m,"shape(stuff,0)==m","1st keyword m","laplace:m=%d",m) {
  /* Processing variable n */
  if (n_capi == Py_None) n = shape(stuff,1); else
    f2py_success = int_from_pyobj(&n,n_capi,"fortran_funcs.laplace() 2nd keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(stuff,1)==n,"shape(stuff,1)==n","2nd keyword n","laplace:n=%d",n) {
  /* Processing variable fuzz */
  fuzz_Dims[0]=m,fuzz_Dims[1]=n;
  capi_fuzz_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_fuzz_tmp = array_from_pyobj(NPY_FLOAT,fuzz_Dims,fuzz_Rank,capi_fuzz_intent,Py_None);
  if (capi_fuzz_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting hidden `fuzz' of fortran_funcs.laplace to C/Fortran array" );
  } else {
    fuzz = (float *)(PyArray_DATA(capi_fuzz_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(stuff,fuzz,&m,&n);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_fuzz_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_fuzz_tmp == NULL) ... else of fuzz*/
  /* End of cleaning variable fuzz */
  } /*CHECKSCALAR(shape(stuff,1)==n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*CHECKSCALAR(shape(stuff,0)==m)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  if((PyObject *)capi_stuff_tmp!=stuff_capi) {
    Py_XDECREF(capi_stuff_tmp); }
  }  /*if (capi_stuff_tmp == NULL) ... else of stuff*/
  /* End of cleaning variable stuff */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of laplace *******************************/

/********************************** interp1 **********************************/
static char doc_f2py_rout_fortran_funcs_interp1[] = "\
yVal = interp1(xData,yData,xVal,[n,m])\n\nWrapper for ``interp1``.\
\n\nParameters\n----------\n"
"xData : input rank-1 array('f') with bounds (n)\n"
"yData : input rank-1 array('f') with bounds (n)\n"
"xVal : input rank-1 array('f') with bounds (m)\n"
"\nOther Parameters\n----------------\n"
"n : input int, optional\n    Default: len(xData)\n"
"m : input int, optional\n    Default: len(xVal)\n"
"\nReturns\n-------\n"
"yVal : rank-1 array('f') with bounds (m)";
/* extern void F_FUNC(interp1,INTERP1)(float*,float*,float*,float*,int*,int*); */
static PyObject *f2py_rout_fortran_funcs_interp1(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *xData = NULL;
  npy_intp xData_Dims[1] = {-1};
  const int xData_Rank = 1;
  PyArrayObject *capi_xData_tmp = NULL;
  int capi_xData_intent = 0;
  PyObject *xData_capi = Py_None;
  float *yData = NULL;
  npy_intp yData_Dims[1] = {-1};
  const int yData_Rank = 1;
  PyArrayObject *capi_yData_tmp = NULL;
  int capi_yData_intent = 0;
  PyObject *yData_capi = Py_None;
  float *xVal = NULL;
  npy_intp xVal_Dims[1] = {-1};
  const int xVal_Rank = 1;
  PyArrayObject *capi_xVal_tmp = NULL;
  int capi_xVal_intent = 0;
  PyObject *xVal_capi = Py_None;
  float *yVal = NULL;
  npy_intp yVal_Dims[1] = {-1};
  const int yVal_Rank = 1;
  PyArrayObject *capi_yVal_tmp = NULL;
  int capi_yVal_intent = 0;
  int n = 0;
  PyObject *n_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  static char *capi_kwlist[] = {"xData","yData","xVal","n","m",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOO|OO:fortran_funcs.interp1",\
    capi_kwlist,&xData_capi,&yData_capi,&xVal_capi,&n_capi,&m_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable xData */
  ;
  capi_xData_intent |= F2PY_INTENT_IN;
  capi_xData_tmp = array_from_pyobj(NPY_FLOAT,xData_Dims,xData_Rank,capi_xData_intent,xData_capi);
  if (capi_xData_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 1st argument `xData' of fortran_funcs.interp1 to C/Fortran array" );
  } else {
    xData = (float *)(PyArray_DATA(capi_xData_tmp));

  /* Processing variable xVal */
  ;
  capi_xVal_intent |= F2PY_INTENT_IN;
  capi_xVal_tmp = array_from_pyobj(NPY_FLOAT,xVal_Dims,xVal_Rank,capi_xVal_intent,xVal_capi);
  if (capi_xVal_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 3rd argument `xVal' of fortran_funcs.interp1 to C/Fortran array" );
  } else {
    xVal = (float *)(PyArray_DATA(capi_xVal_tmp));

  /* Processing variable n */
  if (n_capi == Py_None) n = len(xData); else
    f2py_success = int_from_pyobj(&n,n_capi,"fortran_funcs.interp1() 1st keyword (n) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xData)>=n,"len(xData)>=n","1st keyword n","interp1:n=%d",n) {
  /* Processing variable m */
  if (m_capi == Py_None) m = len(xVal); else
    f2py_success = int_from_pyobj(&m,m_capi,"fortran_funcs.interp1() 2nd keyword (m) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(len(xVal)>=m,"len(xVal)>=m","2nd keyword m","interp1:m=%d",m) {
  /* Processing variable yData */
  yData_Dims[0]=n;
  capi_yData_intent |= F2PY_INTENT_IN;
  capi_yData_tmp = array_from_pyobj(NPY_FLOAT,yData_Dims,yData_Rank,capi_yData_intent,yData_capi);
  if (capi_yData_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 2nd argument `yData' of fortran_funcs.interp1 to C/Fortran array" );
  } else {
    yData = (float *)(PyArray_DATA(capi_yData_tmp));

  /* Processing variable yVal */
  yVal_Dims[0]=m;
  capi_yVal_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_yVal_tmp = array_from_pyobj(NPY_FLOAT,yVal_Dims,yVal_Rank,capi_yVal_intent,Py_None);
  if (capi_yVal_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting hidden `yVal' of fortran_funcs.interp1 to C/Fortran array" );
  } else {
    yVal = (float *)(PyArray_DATA(capi_yVal_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(xData,yData,xVal,yVal,&n,&m);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_yVal_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_yVal_tmp == NULL) ... else of yVal*/
  /* End of cleaning variable yVal */
  if((PyObject *)capi_yData_tmp!=yData_capi) {
    Py_XDECREF(capi_yData_tmp); }
  }  /*if (capi_yData_tmp == NULL) ... else of yData*/
  /* End of cleaning variable yData */
  } /*CHECKSCALAR(len(xVal)>=m)*/
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*CHECKSCALAR(len(xData)>=n)*/
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  if((PyObject *)capi_xVal_tmp!=xVal_capi) {
    Py_XDECREF(capi_xVal_tmp); }
  }  /*if (capi_xVal_tmp == NULL) ... else of xVal*/
  /* End of cleaning variable xVal */
  if((PyObject *)capi_xData_tmp!=xData_capi) {
    Py_XDECREF(capi_xData_tmp); }
  }  /*if (capi_xData_tmp == NULL) ... else of xData*/
  /* End of cleaning variable xData */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of interp1 *******************************/

/********************************* curvature *********************************/
static char doc_f2py_rout_fortran_funcs_curvature[] = "\
omega_c = curvature(dem_in,eta,[ny,nx])\n\nWrapper for ``curvature``.\
\n\nParameters\n----------\n"
"dem_in : input rank-2 array('f') with bounds (ny,nx)\n"
"eta : input float\n"
"\nOther Parameters\n----------------\n"
"ny : input int, optional\n    Default: shape(dem_in,0)\n"
"nx : input int, optional\n    Default: shape(dem_in,1)\n"
"\nReturns\n-------\n"
"omega_c : rank-2 array('f') with bounds (ny,nx)";
/* extern void F_FUNC(curvature,CURVATURE)(float*,float*,int*,int*,float*); */
static PyObject *f2py_rout_fortran_funcs_curvature(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,int*,int*,float*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *dem_in = NULL;
  npy_intp dem_in_Dims[2] = {-1, -1};
  const int dem_in_Rank = 2;
  PyArrayObject *capi_dem_in_tmp = NULL;
  int capi_dem_in_intent = 0;
  PyObject *dem_in_capi = Py_None;
  float eta = 0;
  PyObject *eta_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nx = 0;
  PyObject *nx_capi = Py_None;
  float *omega_c = NULL;
  npy_intp omega_c_Dims[2] = {-1, -1};
  const int omega_c_Rank = 2;
  PyArrayObject *capi_omega_c_tmp = NULL;
  int capi_omega_c_intent = 0;
  static char *capi_kwlist[] = {"dem_in","eta","ny","nx",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OO|OO:fortran_funcs.curvature",\
    capi_kwlist,&dem_in_capi,&eta_capi,&ny_capi,&nx_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable dem_in */
  ;
  capi_dem_in_intent |= F2PY_INTENT_IN;
  capi_dem_in_tmp = array_from_pyobj(NPY_FLOAT,dem_in_Dims,dem_in_Rank,capi_dem_in_intent,dem_in_capi);
  if (capi_dem_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 1st argument `dem_in' of fortran_funcs.curvature to C/Fortran array" );
  } else {
    dem_in = (float *)(PyArray_DATA(capi_dem_in_tmp));

  /* Processing variable eta */
    f2py_success = float_from_pyobj(&eta,eta_capi,"fortran_funcs.curvature() 2nd argument (eta) can't be converted to float");
  if (f2py_success) {
  /* Processing variable ny */
  if (ny_capi == Py_None) ny = shape(dem_in,0); else
    f2py_success = int_from_pyobj(&ny,ny_capi,"fortran_funcs.curvature() 1st keyword (ny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(dem_in,0)==ny,"shape(dem_in,0)==ny","1st keyword ny","curvature:ny=%d",ny) {
  /* Processing variable nx */
  if (nx_capi == Py_None) nx = shape(dem_in,1); else
    f2py_success = int_from_pyobj(&nx,nx_capi,"fortran_funcs.curvature() 2nd keyword (nx) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(dem_in,1)==nx,"shape(dem_in,1)==nx","2nd keyword nx","curvature:nx=%d",nx) {
  /* Processing variable omega_c */
  omega_c_Dims[0]=ny,omega_c_Dims[1]=nx;
  capi_omega_c_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_omega_c_tmp = array_from_pyobj(NPY_FLOAT,omega_c_Dims,omega_c_Rank,capi_omega_c_intent,Py_None);
  if (capi_omega_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting hidden `omega_c' of fortran_funcs.curvature to C/Fortran array" );
  } else {
    omega_c = (float *)(PyArray_DATA(capi_omega_c_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(dem_in,&eta,&ny,&nx,omega_c);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_omega_c_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_omega_c_tmp == NULL) ... else of omega_c*/
  /* End of cleaning variable omega_c */
  } /*CHECKSCALAR(shape(dem_in,1)==nx)*/
  } /*if (f2py_success) of nx*/
  /* End of cleaning variable nx */
  } /*CHECKSCALAR(shape(dem_in,0)==ny)*/
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  } /*if (f2py_success) of eta*/
  /* End of cleaning variable eta */
  if((PyObject *)capi_dem_in_tmp!=dem_in_capi) {
    Py_XDECREF(capi_dem_in_tmp); }
  }  /*if (capi_dem_in_tmp == NULL) ... else of dem_in*/
  /* End of cleaning variable dem_in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of curvature ******************************/

/********************************** zinterp **********************************/
static char doc_f2py_rout_fortran_funcs_zinterp[] = "\
v_out = zinterp(z_in,z_out,v_in,vsfc_in,vele_in,[nx,ny,nz1,nz2])\n\nWrapper for ``zinterp``.\
\n\nParameters\n----------\n"
"z_in : input rank-3 array('f') with bounds (nz1,ny,nx)\n"
"z_out : input rank-3 array('f') with bounds (nz2,ny,nx)\n"
"v_in : input rank-3 array('f') with bounds (nz1,ny,nx)\n"
"vsfc_in : input rank-2 array('f') with bounds (ny,nx)\n"
"vele_in : input rank-2 array('f') with bounds (ny,nx)\n"
"\nOther Parameters\n----------------\n"
"nx : input int, optional\n    Default: shape(z_in,2)\n"
"ny : input int, optional\n    Default: shape(z_in,1)\n"
"nz1 : input int, optional\n    Default: shape(z_in,0)\n"
"nz2 : input int, optional\n    Default: shape(z_out,0)\n"
"\nReturns\n-------\n"
"v_out : rank-3 array('f') with bounds (nz2,ny,nx)";
/* extern void F_FUNC(zinterp,ZINTERP)(float*,float*,float*,float*,float*,float*,int*,int*,int*,int*); */
static PyObject *f2py_rout_fortran_funcs_zinterp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(float*,float*,float*,float*,float*,float*,int*,int*,int*,int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  float *z_in = NULL;
  npy_intp z_in_Dims[3] = {-1, -1, -1};
  const int z_in_Rank = 3;
  PyArrayObject *capi_z_in_tmp = NULL;
  int capi_z_in_intent = 0;
  PyObject *z_in_capi = Py_None;
  float *z_out = NULL;
  npy_intp z_out_Dims[3] = {-1, -1, -1};
  const int z_out_Rank = 3;
  PyArrayObject *capi_z_out_tmp = NULL;
  int capi_z_out_intent = 0;
  PyObject *z_out_capi = Py_None;
  float *v_in = NULL;
  npy_intp v_in_Dims[3] = {-1, -1, -1};
  const int v_in_Rank = 3;
  PyArrayObject *capi_v_in_tmp = NULL;
  int capi_v_in_intent = 0;
  PyObject *v_in_capi = Py_None;
  float *vsfc_in = NULL;
  npy_intp vsfc_in_Dims[2] = {-1, -1};
  const int vsfc_in_Rank = 2;
  PyArrayObject *capi_vsfc_in_tmp = NULL;
  int capi_vsfc_in_intent = 0;
  PyObject *vsfc_in_capi = Py_None;
  float *vele_in = NULL;
  npy_intp vele_in_Dims[2] = {-1, -1};
  const int vele_in_Rank = 2;
  PyArrayObject *capi_vele_in_tmp = NULL;
  int capi_vele_in_intent = 0;
  PyObject *vele_in_capi = Py_None;
  float *v_out = NULL;
  npy_intp v_out_Dims[3] = {-1, -1, -1};
  const int v_out_Rank = 3;
  PyArrayObject *capi_v_out_tmp = NULL;
  int capi_v_out_intent = 0;
  int nx = 0;
  PyObject *nx_capi = Py_None;
  int ny = 0;
  PyObject *ny_capi = Py_None;
  int nz1 = 0;
  PyObject *nz1_capi = Py_None;
  int nz2 = 0;
  PyObject *nz2_capi = Py_None;
  static char *capi_kwlist[] = {"z_in","z_out","v_in","vsfc_in","vele_in","nx","ny","nz1","nz2",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOO|OOOO:fortran_funcs.zinterp",\
    capi_kwlist,&z_in_capi,&z_out_capi,&v_in_capi,&vsfc_in_capi,&vele_in_capi,&nx_capi,&ny_capi,&nz1_capi,&nz2_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable z_in */
  ;
  capi_z_in_intent |= F2PY_INTENT_IN;
  capi_z_in_tmp = array_from_pyobj(NPY_FLOAT,z_in_Dims,z_in_Rank,capi_z_in_intent,z_in_capi);
  if (capi_z_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 1st argument `z_in' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    z_in = (float *)(PyArray_DATA(capi_z_in_tmp));

  /* Processing variable nx */
  if (nx_capi == Py_None) nx = shape(z_in,2); else
    f2py_success = int_from_pyobj(&nx,nx_capi,"fortran_funcs.zinterp() 1st keyword (nx) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(z_in,2)==nx,"shape(z_in,2)==nx","1st keyword nx","zinterp:nx=%d",nx) {
  /* Processing variable ny */
  if (ny_capi == Py_None) ny = shape(z_in,1); else
    f2py_success = int_from_pyobj(&ny,ny_capi,"fortran_funcs.zinterp() 2nd keyword (ny) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(z_in,1)==ny,"shape(z_in,1)==ny","2nd keyword ny","zinterp:ny=%d",ny) {
  /* Processing variable nz1 */
  if (nz1_capi == Py_None) nz1 = shape(z_in,0); else
    f2py_success = int_from_pyobj(&nz1,nz1_capi,"fortran_funcs.zinterp() 3rd keyword (nz1) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(z_in,0)==nz1,"shape(z_in,0)==nz1","3rd keyword nz1","zinterp:nz1=%d",nz1) {
  /* Processing variable v_in */
  v_in_Dims[0]=nz1,v_in_Dims[1]=ny,v_in_Dims[2]=nx;
  capi_v_in_intent |= F2PY_INTENT_IN;
  capi_v_in_tmp = array_from_pyobj(NPY_FLOAT,v_in_Dims,v_in_Rank,capi_v_in_intent,v_in_capi);
  if (capi_v_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 3rd argument `v_in' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    v_in = (float *)(PyArray_DATA(capi_v_in_tmp));

  /* Processing variable z_out */
  z_out_Dims[1]=ny,z_out_Dims[2]=nx;
  capi_z_out_intent |= F2PY_INTENT_IN;
  capi_z_out_tmp = array_from_pyobj(NPY_FLOAT,z_out_Dims,z_out_Rank,capi_z_out_intent,z_out_capi);
  if (capi_z_out_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 2nd argument `z_out' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    z_out = (float *)(PyArray_DATA(capi_z_out_tmp));

  /* Processing variable vsfc_in */
  vsfc_in_Dims[0]=ny,vsfc_in_Dims[1]=nx;
  capi_vsfc_in_intent |= F2PY_INTENT_IN;
  capi_vsfc_in_tmp = array_from_pyobj(NPY_FLOAT,vsfc_in_Dims,vsfc_in_Rank,capi_vsfc_in_intent,vsfc_in_capi);
  if (capi_vsfc_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 4th argument `vsfc_in' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    vsfc_in = (float *)(PyArray_DATA(capi_vsfc_in_tmp));

  /* Processing variable vele_in */
  vele_in_Dims[0]=ny,vele_in_Dims[1]=nx;
  capi_vele_in_intent |= F2PY_INTENT_IN;
  capi_vele_in_tmp = array_from_pyobj(NPY_FLOAT,vele_in_Dims,vele_in_Rank,capi_vele_in_intent,vele_in_capi);
  if (capi_vele_in_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting 5th argument `vele_in' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    vele_in = (float *)(PyArray_DATA(capi_vele_in_tmp));

  /* Processing variable nz2 */
  if (nz2_capi == Py_None) nz2 = shape(z_out,0); else
    f2py_success = int_from_pyobj(&nz2,nz2_capi,"fortran_funcs.zinterp() 4th keyword (nz2) can't be converted to int");
  if (f2py_success) {
  CHECKSCALAR(shape(z_out,0)==nz2,"shape(z_out,0)==nz2","4th keyword nz2","zinterp:nz2=%d",nz2) {
  /* Processing variable v_out */
  v_out_Dims[0]=nz2,v_out_Dims[1]=ny,v_out_Dims[2]=nx;
  capi_v_out_intent |= F2PY_INTENT_OUT|F2PY_INTENT_HIDE;
  capi_v_out_tmp = array_from_pyobj(NPY_FLOAT,v_out_Dims,v_out_Rank,capi_v_out_intent,Py_None);
  if (capi_v_out_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(fortran_funcs_error,"failed in converting hidden `v_out' of fortran_funcs.zinterp to C/Fortran array" );
  } else {
    v_out = (float *)(PyArray_DATA(capi_v_out_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(z_in,z_out,v_in,vsfc_in,vele_in,v_out,&nx,&ny,&nz1,&nz2);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_v_out_tmp);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  }  /*if (capi_v_out_tmp == NULL) ... else of v_out*/
  /* End of cleaning variable v_out */
  } /*CHECKSCALAR(shape(z_out,0)==nz2)*/
  } /*if (f2py_success) of nz2*/
  /* End of cleaning variable nz2 */
  if((PyObject *)capi_vele_in_tmp!=vele_in_capi) {
    Py_XDECREF(capi_vele_in_tmp); }
  }  /*if (capi_vele_in_tmp == NULL) ... else of vele_in*/
  /* End of cleaning variable vele_in */
  if((PyObject *)capi_vsfc_in_tmp!=vsfc_in_capi) {
    Py_XDECREF(capi_vsfc_in_tmp); }
  }  /*if (capi_vsfc_in_tmp == NULL) ... else of vsfc_in*/
  /* End of cleaning variable vsfc_in */
  if((PyObject *)capi_z_out_tmp!=z_out_capi) {
    Py_XDECREF(capi_z_out_tmp); }
  }  /*if (capi_z_out_tmp == NULL) ... else of z_out*/
  /* End of cleaning variable z_out */
  if((PyObject *)capi_v_in_tmp!=v_in_capi) {
    Py_XDECREF(capi_v_in_tmp); }
  }  /*if (capi_v_in_tmp == NULL) ... else of v_in*/
  /* End of cleaning variable v_in */
  } /*CHECKSCALAR(shape(z_in,0)==nz1)*/
  } /*if (f2py_success) of nz1*/
  /* End of cleaning variable nz1 */
  } /*CHECKSCALAR(shape(z_in,1)==ny)*/
  } /*if (f2py_success) of ny*/
  /* End of cleaning variable ny */
  } /*CHECKSCALAR(shape(z_in,2)==nx)*/
  } /*if (f2py_success) of nx*/
  /* End of cleaning variable nx */
  if((PyObject *)capi_z_in_tmp!=z_in_capi) {
    Py_XDECREF(capi_z_in_tmp); }
  }  /*if (capi_z_in_tmp == NULL) ... else of z_in*/
  /* End of cleaning variable z_in */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of zinterp *******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"laplace",-1,{{-1}},0,(char *)F_FUNC(laplace,LAPLACE),(f2py_init_func)f2py_rout_fortran_funcs_laplace,doc_f2py_rout_fortran_funcs_laplace},
  {"interp1",-1,{{-1}},0,(char *)F_FUNC(interp1,INTERP1),(f2py_init_func)f2py_rout_fortran_funcs_interp1,doc_f2py_rout_fortran_funcs_interp1},
  {"curvature",-1,{{-1}},0,(char *)F_FUNC(curvature,CURVATURE),(f2py_init_func)f2py_rout_fortran_funcs_curvature,doc_f2py_rout_fortran_funcs_curvature},
  {"zinterp",-1,{{-1}},0,(char *)F_FUNC(zinterp,ZINTERP),(f2py_init_func)f2py_rout_fortran_funcs_zinterp,doc_f2py_rout_fortran_funcs_zinterp},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "fortran_funcs",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_fortran_funcs(void) {
#else
#define RETVAL
PyMODINIT_FUNC initfortran_funcs(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = fortran_funcs_module = PyModule_Create(&moduledef);
#else
  m = fortran_funcs_module = Py_InitModule("fortran_funcs", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module fortran_funcs (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'fortran_funcs' is auto-generated with f2py (version:2).\nFunctions:\n"
"  fuzz = laplace(stuff,m=shape(stuff,0),n=shape(stuff,1))\n"
"  yVal = interp1(xData,yData,xVal,n=len(xData),m=len(xVal))\n"
"  omega_c = curvature(dem_in,eta,ny=shape(dem_in,0),nx=shape(dem_in,1))\n"
"  v_out = zinterp(z_in,z_out,v_in,vsfc_in,vele_in,nx=shape(z_in,2),ny=shape(z_in,1),nz1=shape(z_in,0),nz2=shape(z_out,0))\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  fortran_funcs_error = PyErr_NewException ("fortran_funcs.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"fortran_funcs");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
